### PR TITLE
Deal with uri key in databrowser

### PR DESCRIPTION
**Pull request by antarcticrainforest**
This deals with the updated solr scheme, where an new unique key called uri was added.

### CODE REVIEW

**Review by Karinon — APPROVED** [review]
I am not sure if I get all the implications, but for now LGTM

**Comment by antarcticrainforest** [comment]
Test are passing.

**Comment by antarcticrainforest** [comment]
@eelucio is this ok?

**Comment by eelucio** [comment]
yes, LGTM

**Review by eelucio — APPROVED** [review]

**Pull request merged**
