### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by grooverdan**

### CODE REVIEW

**Review by antarcticrainforest — APPROVED** [review]

**Comment by antarcticrainforest** [comment]
Thanks heaps!

**Comment by grooverdan** [comment]
I meant to test this a lot more and was looking to test on CI of my fork but failed. Local testing using buildah wasn't seeing the .docker directory on COPY so please test again properly.

Appoligies if I stuffed up anything.

**Comment by antarcticrainforest** [comment]
No worries, I should have had my morning coffee before clicking buttons. Will fix this. Thanks for your help, very much appreciated!

**Comment by grooverdan** [comment]
:coffee:  . Thanks.

**Pull request merged**
