### PR TITLE
Quick Fix: Improve rich console logger.

### PR DESCRIPTION
**Pull request by antarcticrainforest**
This improves the logger output that is displayed in jupyter notebooks.

### CODE REVIEW

**Comment by eelucio** [comment]
Lgtm

**Comment by antarcticrainforest** [comment]
The tests are failing, unfortunately I  can't see why.

**Comment by tropicrainforest** [comment]
> The tests are failing, unfortunately I can't see why.

@antarcticrainforest, I've noticed an issue with the latest version of the MariaDB image! It was working well on my machine but on github action NO! To resolve the current red pipeline and fix  MariaDB lost connection in our CI jobs, I've rolled back to version 11.3 [here](https://github.com/FREVA-CLINT/freva/blob/console-logger-fix/docker-compose.yaml#L4), which was working fine and I got connected MariDB, and green pipeline in result ...

@grooverdan FYI

**Comment by antarcticrainforest** [comment]
> > The tests are failing, unfortunately I can't see why.
> 
> @antarcticrainforest, I've noticed an issue with the latest version of the MariaDB image! It was working well on my machine but on github action NO! To resolve the current red pipeline and fix MariaDB lost connection in our CI jobs, I've rolled back to version 11.3 [here](https://github.com/FREVA-CLINT/freva/blob/console-logger-fix/docker-compose.yaml#L4), which was working fine and I got connected MariDB, and green pipeline in result ...
> 
> @grooverdan FYI

Thanks for the hint @MoSHad91

**Comment by grooverdan** [comment]
From [this](https://github.com/FREVA-CLINT/freva/actions/runs/9450010768/job/26027628307) there is:
```
0.097 + groupadd -r --gid 1000 freva
0.099 groupadd: GID '1000' already exists
```

MariaDB 11.4 is a Ubuntu noble base and < 11.3 is jammy (or focal for 10.4).

Ubuntu has added a user to the base container MariaDB uses:
```
$ podman run --rm  mariadb:11.4 bash -c 'getent group 1000 ; id 1000'
ubuntu:x:1000:
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev)
```

I'm fairly sure I can remove this user without impact. If you do add a `userdel` / `groupdel` can you make it non fatal for when I update the image.

Alternate mariadb:11.4-ubi is a UBI based image. That doesn't have a id 1000. I couldn't obviously see anything in your Dockerfile that was ubuntu specific so that may work too.

**Comment by grooverdan** [comment]
#204 - quick fix

**Comment by grooverdan** [comment]
FYI I've taken the default ubuntu user out of the noble based images - https://github.com/MariaDB/mariadb-docker/commit/fb46c566261b95c3d19e9aaaa147b1c12d332868 - you could revert #204 optionally if you want only newer stable images.

**Comment by tropicrainforest** [comment]
> FYI I've taken the default ubuntu user out of the noble based images - [MariaDB/mariadb-docker@fb46c56](https://github.com/MariaDB/mariadb-docker/commit/fb46c566261b95c3d19e9aaaa147b1c12d332868) - you could revert #204 optionally if you want only newer stable images.

Thanks @grooverdan, I explained the current issue with more detail in https://github.com/FREVA-CLINT/freva/pull/236

**Pull request merged**
